import { requireAdmin } from "@/lib/auth";
import { CollectionHeader, SaveButton, TextArea, TextField } from "@/components/admin-form-fields";
import { addBlockedPeriod, addPricingRule, saveBookingRules, saveStudio } from "./actions";

export default async function StudioAdmin() {
  const { supabase } = await requireAdmin();
  const { data: studio, error } = await supabase.from("studios").select("*").eq("slug", "studio-two").single();
  if (error) throw new Error(error.message);
  const [{ data: blocks }, { data: prices }, { data: rules }] = await Promise.all([
    supabase.from("blocked_periods").select("*").eq("studio_id", studio.id).order("starts_at"),
    supabase.from("pricing_rules").select("*").eq("studio_id", studio.id).order("priority"),
    supabase.from("booking_rules").select("*").eq("studio_id", studio.id).maybeSingle(),
  ]);
  return <><CollectionHeader eyebrow="Operations" title="Studio configuration" description="Manage studio details, booking constraints, blocked periods, and pricing."/><div className="mt-8 grid gap-8">
    <form action={saveStudio} className="grid gap-4 bg-paper p-6"><h2 className="font-display text-2xl">Studio details</h2><input type="hidden" name="id" value={studio.id}/><div className="grid gap-4 sm:grid-cols-2"><TextField name="name" label="Name" value={studio.name} required/><TextField name="slug" label="Slug" value={studio.slug} required/></div><TextArea name="description" label="Description" value={studio.description}/><TextArea name="address" label="Address" value={studio.address}/><div className="grid gap-4 sm:grid-cols-2"><TextField name="timezone" label="Timezone" value={studio.timezone}/><TextField name="currency" label="Currency" value={studio.currency}/></div><label className="text-sm"><input type="checkbox" name="active" defaultChecked={studio.active} className="mr-2"/>Active</label><SaveButton/></form>
    <form action={saveBookingRules} className="grid gap-4 bg-paper p-6"><h2 className="font-display text-2xl">Booking rules</h2><input type="hidden" name="studio_id" value={studio.id}/><div className="grid gap-4 sm:grid-cols-3"><TextField name="minimum_duration_minutes" label="Minimum duration (minutes)" type="number" value={rules?.minimum_duration_minutes||60}/><TextField name="maximum_duration_minutes" label="Maximum duration (minutes)" type="number" value={rules?.maximum_duration_minutes||720}/><TextField name="booking_increment_minutes" label="Increment (minutes)" type="number" value={rules?.booking_increment_minutes||30}/><TextField name="minimum_notice_hours" label="Minimum notice (hours)" type="number" value={rules?.minimum_notice_hours||24}/><TextField name="maximum_advance_days" label="Maximum advance (days)" type="number" value={rules?.maximum_advance_days||365}/><TextField name="hold_duration_minutes" label="Hold duration (minutes)" type="number" value={rules?.hold_duration_minutes||15}/></div><TextArea name="cancellation_policy" label="Cancellation policy" value={rules?.cancellation_policy}/><SaveButton/></form>
    <div className="grid gap-8 lg:grid-cols-2"><section className="bg-paper p-6"><h2 className="font-display text-2xl">Blocked periods</h2><form action={addBlockedPeriod} className="mt-5 grid gap-4"><input type="hidden" name="studio_id" value={studio.id}/><TextField name="starts_at" label="Starts" type="datetime-local" required/><TextField name="ends_at" label="Ends" type="datetime-local" required/><TextField name="reason" label="Reason" required/><TextArea name="internal_notes" label="Internal notes"/><SaveButton label="Block period"/></form><div className="mt-6 space-y-2">{blocks?.map(block=><p key={block.id} className="border-t border-black/10 pt-2 text-sm"><strong>{block.reason}</strong><br/><span className="text-black/50">{new Date(block.starts_at).toLocaleString()} – {new Date(block.ends_at).toLocaleString()}</span></p>)}</div></section>
    <section className="bg-paper p-6"><h2 className="font-display text-2xl">Pricing rules</h2><form action={addPricingRule} className="mt-5 grid gap-4"><input type="hidden" name="studio_id" value={studio.id}/><TextField name="name" label="Rule name" required/><label className="text-sm"><span className="mb-2 block">Type</span><select name="rule_type" className="w-full border border-black/15 bg-white px-3 py-2.5"><option value="hourly">Hourly</option><option value="fixed">Fixed</option><option value="tiered">Tiered</option><option value="percentage">Percentage</option><option value="flat_fee">Flat fee</option></select></label><TextField name="amount" label={`Amount (${studio.currency})`} type="number" value={0}/><TextField name="priority" label="Priority" type="number" value={0}/><label className="text-sm"><input type="checkbox" name="active" defaultChecked className="mr-2"/>Active</label><SaveButton label="Add pricing rule"/></form><div className="mt-6 space-y-2">{prices?.map(price=><p key={price.id} className="flex justify-between border-t border-black/10 pt-2 text-sm"><span>{price.name}<br/><small className="text-black/45">{price.rule_type}</small></span><strong>{studio.currency} {(price.amount_minor/100).toFixed(2)}</strong></p>)}</div></section></div>
  </div></>;
}
