"use client";
import Image from "next/image";
import { Eye, Pencil, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { ActionForm } from "@/components/action-form";
import { SaveButton, StatusField, TextArea, TextField } from "@/components/admin-form-fields";
import { deleteGalleryItem, saveGalleryItem } from "@/app/admin/website/content-actions";
type GalleryItem = { id:string;title:string;description:string|null;media_url:string;media_type:string;category:string;featured:boolean;sort_order:number;status:string };
export function GalleryManager({items}:{items:GalleryItem[]}){const[editing,setEditing]=useState<GalleryItem|"new"|null>(null),[viewing,setViewing]=useState<GalleryItem|null>(null);return <><div className="mt-8 flex justify-end"><button type="button" onClick={()=>setEditing("new")} className="inline-flex items-center gap-2 bg-ink px-4 py-3 text-sm text-paper transition hover:bg-gold hover:text-ink"><Plus size={17}/> Add gallery image</button></div><div className="mt-4 overflow-x-auto border border-black/10 bg-paper"><table className="w-full min-w-[48rem] text-left text-sm"><thead className="border-b border-black/10 text-black/45"><tr><th className="p-4">Thumbnail</th><th className="p-4">Title</th><th className="p-4">Category</th><th className="p-4">Status</th><th className="p-4">Featured</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b border-black/10 transition hover:bg-white"><td className="p-3"><Image src={item.media_url} alt={item.title} width={96} height={64} className="h-14 w-20 object-cover" unoptimized/></td><td className="p-4 font-medium">{item.title}</td><td className="p-4">{item.category}</td><td className="p-4 capitalize">{item.status}</td><td className="p-4">{item.featured?"Yes":"No"}</td><td className="p-4"><div className="flex justify-end gap-2"><Icon label="View" onClick={()=>setViewing(item)}><Eye size={16}/></Icon><Icon label="Edit" onClick={()=>setEditing(item)}><Pencil size={16}/></Icon><ActionForm action={deleteGalleryItem} successMessage={`${item.title} deleted.`} className="inline"><input type="hidden" name="id" value={item.id}/><button aria-label={`Delete ${item.title}`} className="grid size-9 place-items-center border border-black/15 text-red-700 transition hover:bg-red-700 hover:text-white"><Trash2 size={16}/></button></ActionForm></div></td></tr>)}</tbody></table>{!items.length&&<p className="p-6 text-sm text-black/50">No gallery images have been added yet.</p>}</div>{editing&&<Modal title={editing==="new"?"Add gallery image":`Edit ${editing.title}`} close={()=>setEditing(null)}><GalleryForm item={editing==="new"?undefined:editing}/></Modal>}{viewing&&<Modal title={viewing.title} close={()=>setViewing(null)}><Image src={viewing.media_url} alt={viewing.title} width={1200} height={800} className="max-h-[65vh] w-full object-contain" unoptimized/><p className="mt-4 leading-7 text-black/60">{viewing.description||"No description."}</p></Modal>}</>}
function GalleryForm({item}:{item?:GalleryItem}){return <ActionForm action={saveGalleryItem} successMessage={item?"Gallery image saved.":"Gallery image added."} className="grid gap-4"><input type="hidden" name="id" value={item?.id||""}/><input type="hidden" name="current_media_url" value={item?.media_url||""}/><TextField name="title" label="Title" value={item?.title} required/><TextArea name="description" label="Description" value={item?.description}/><label className="text-sm"><span className="mb-2 block">Image file</span><input type="file" name="image" required={!item} accept="image/jpeg,image/png,image/webp,image/gif" className="w-full border border-black/15 bg-white px-3 py-2.5"/></label><div className="grid gap-4 sm:grid-cols-3"><TextField name="category" label="Category" value={item?.category||"Studio"} required/><TextField name="sort_order" label="Sort order" type="number" value={item?.sort_order||0}/><StatusField value={item?.status||"draft"}/></div><label className="text-sm"><input type="checkbox" name="featured" defaultChecked={item?.featured} className="mr-2"/>Featured</label><SaveButton label={item?"Save changes":"Add image"}/></ActionForm>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[60] grid place-items-center overflow-y-auto bg-black/55 p-4"><section role="dialog" aria-modal="true" className="my-8 w-full max-w-3xl bg-paper p-6"><div className="mb-6 flex items-center justify-between"><h2 className="font-display text-3xl">{title}</h2><button type="button" aria-label="Close" onClick={close}><X/></button></div>{children}</section></div>}
function Icon({label,onClick,children}:{label:string;onClick:()=>void;children:React.ReactNode}){return <button type="button" aria-label={label} title={label} onClick={onClick} className="grid size-9 place-items-center border border-black/15 transition hover:bg-gold">{children}</button>}
