"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { uploadImage } from "@/lib/upload-image";
const status=z.enum(["draft","published","archived"]),optionalId=z.union([z.literal(""),z.uuid()]),text=(max=500)=>z.string().trim().max(max);
async function save(table:string,id:string,values:Record<string,unknown>,path:string){const{supabase}=await requireAdmin();const query=id?supabase.from(table).update(values).eq("id",id):supabase.from(table).insert(values);const{error}=await query;if(error)throw new Error(error.message);revalidatePath(path)}
export async function saveFaq(form:FormData){const v=z.object({id:optionalId,question:text(300).min(1),answer:text(5000).min(1),category:text(80).min(1),sort_order:z.coerce.number().int().min(0),status}).parse(Object.fromEntries(form));await save("faqs",v.id,{question:v.question,answer:v.answer,category:v.category,sort_order:v.sort_order,status:v.status},"/admin/website/faqs");revalidatePath("/faq");revalidatePath("/")}
export async function deleteFaq(form:FormData){const id=z.uuid().parse(form.get("id"));const{supabase}=await requireAdmin();const{error}=await supabase.from("faqs").delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/website/faqs");revalidatePath("/faq");revalidatePath("/")}
export async function saveTestimonial(form:FormData){const v=z.object({id:optionalId,customer_name:text(120).min(1),customer_role:text(120),company:text(120),review:text(3000).min(1),rating:z.coerce.number().int().min(1).max(5),current_profile_image_url:z.string().optional().default(""),sort_order:z.coerce.number().int().min(0),status}).parse(Object.fromEntries(form));const{supabase,user}=await requireAdmin();const profile_image_url=await uploadImage(supabase,user.id,form.get("profile_image"),v.current_profile_image_url);await save("testimonials",v.id,{customer_name:v.customer_name,customer_role:v.customer_role,company:v.company,review:v.review,rating:v.rating,profile_image_url,sort_order:v.sort_order,status:v.status},"/admin/website/testimonials")}
export async function saveGalleryItem(form:FormData){const v=z.object({id:optionalId,title:text(160).min(1),description:text(1000),current_media_url:z.string().optional().default(""),category:text(80).min(1),featured:z.string().optional(),sort_order:z.coerce.number().int().min(0),status}).parse(Object.fromEntries(form));const{supabase,user}=await requireAdmin();const media_url=await uploadImage(supabase,user.id,form.get("image"),v.current_media_url);if(!media_url)throw new Error("Choose an image.");await save("gallery_items",v.id,{title:v.title,description:v.description||null,media_url,media_type:"image",category:v.category,featured:v.featured==="on",sort_order:v.sort_order,status:v.status},"/admin/website/gallery")}
export async function deleteGalleryItem(form:FormData){const id=z.uuid().parse(form.get("id"));const{supabase}=await requireAdmin();const{error}=await supabase.from("gallery_items").delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/website/gallery");revalidatePath("/gallery");revalidatePath("/")}
export async function saveNavigationItem(form:FormData){const v=z.object({id:optionalId,label:text(80).min(1),url:text(500).min(1),sort_order:z.coerce.number().int().min(0),is_visible:z.string().optional(),opens_new_tab:z.string().optional(),status}).parse(Object.fromEntries(form));await save("navigation_items",v.id,{label:v.label,url:v.url,sort_order:v.sort_order,is_visible:v.is_visible==="on",opens_new_tab:v.opens_new_tab==="on",status:v.status},"/admin/website/navigation")}
export async function saveFooter(form:FormData){const v=z.object({description:text(1000),address:text(500),phone:text(80),email:z.union([z.literal(""),z.email()]),opening_hours:text(1000),copyright:text(300),status}).parse(Object.fromEntries(form));const{supabase,user}=await requireAdmin();const{status:state,...value}=v;const{error}=await supabase.from("site_settings").upsert({key:"footer",value,status:state,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/admin/website/footer")}
export async function uploadMedia(form:FormData){const file=form.get("file"),alt=text(300).parse(form.get("alt_text")||"");if(!(file instanceof File)||file.size===0||file.size>10485760)throw new Error("Choose an image up to 10 MB.");const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]);if(!allowed.has(file.type))throw new Error("Upload a JPG, PNG, WebP, or GIF image.");const{supabase,user}=await requireAdmin();const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${user.id}/${crypto.randomUUID()}-${safeName}`;const{error:uploadError}=await supabase.storage.from("media").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw new Error(uploadError.message);const{error}=await supabase.from("media_assets").insert({file_name:file.name,storage_path:path,media_type:"image",mime_type:file.type,file_size:file.size,alt_text:alt||null,title:file.name,uploaded_by:user.id});if(error){await supabase.storage.from("media").remove([path]);throw new Error(error.message)}revalidatePath("/admin/website/media")}
