"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";

const status = z.enum(["draft", "published", "archived"]);
const optionalId = z.union([z.literal(""), z.uuid()]);
const text = (max = 500) => z.string().trim().max(max);
async function save(table: string, id: string, values: Record<string, unknown>, path: string) { const { supabase } = await requireAdmin(); const query = id ? supabase.from(table).update(values).eq("id", id) : supabase.from(table).insert(values); const { error } = await query; if (error) throw new Error(error.message); revalidatePath(path); }

export async function saveFaq(form: FormData) { const v = z.object({ id: optionalId, question: text(300).min(1), answer: text(5000).min(1), category: text(80).min(1), sort_order: z.coerce.number().int().min(0), status }).parse(Object.fromEntries(form)); await save("faqs", v.id, { question:v.question, answer:v.answer, category:v.category, sort_order:v.sort_order, status:v.status }, "/admin/website/faqs"); }
export async function saveTestimonial(form: FormData) { const v = z.object({ id: optionalId, customer_name:text(120).min(1), customer_role:text(120), company:text(120), review:text(3000).min(1), rating:z.coerce.number().int().min(1).max(5), profile_image_url:z.union([z.literal(""),z.url()]), sort_order:z.coerce.number().int().min(0), status }).parse(Object.fromEntries(form)); await save("testimonials", v.id, { ...v, id:undefined, profile_image_url:v.profile_image_url||null }, "/admin/website/testimonials"); }
export async function saveGalleryItem(form: FormData) { const raw = Object.fromEntries(form); const v = z.object({ id:optionalId, title:text(160).min(1), description:text(1000), media_url:z.url(), media_type:z.enum(["image","video"]), category:text(80).min(1), featured:z.string().optional(), sort_order:z.coerce.number().int().min(0), status }).parse(raw); await save("gallery_items", v.id, { title:v.title, description:v.description||null, media_url:v.media_url, media_type:v.media_type, category:v.category, featured:v.featured==="on", sort_order:v.sort_order, status:v.status }, "/admin/website/gallery"); }
export async function saveNavigationItem(form: FormData) { const v = z.object({ id:optionalId, label:text(80).min(1), url:text(500).min(1), sort_order:z.coerce.number().int().min(0), is_visible:z.string().optional(), opens_new_tab:z.string().optional(), status }).parse(Object.fromEntries(form)); await save("navigation_items", v.id, { label:v.label, url:v.url, sort_order:v.sort_order, is_visible:v.is_visible==="on", opens_new_tab:v.opens_new_tab==="on", status:v.status }, "/admin/website/navigation"); }
export async function saveFooter(form: FormData) { const v = z.object({ description:text(1000), address:text(500), phone:text(80), email:z.union([z.literal(""),z.email()]), opening_hours:text(1000), copyright:text(300), status }).parse(Object.fromEntries(form)); const { supabase, user } = await requireAdmin(); const { status: state, ...value } = v; const { error } = await supabase.from("site_settings").upsert({ key:"footer", value, status:state, updated_by:user.id }); if (error) throw new Error(error.message); revalidatePath("/admin/website/footer"); }
export async function uploadMedia(form: FormData) { const file = form.get("file"); const alt = text(300).parse(form.get("alt_text")||""); if (!(file instanceof File) || file.size===0 || file.size>10485760) throw new Error("Choose a file up to 10 MB."); const allowed = new Set(["image/jpeg","image/png","image/webp","image/gif","video/mp4","application/pdf"]); if (!allowed.has(file.type)) throw new Error("Unsupported file type."); const { supabase, user } = await requireAdmin(); const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"); const path=`${user.id}/${crypto.randomUUID()}-${safeName}`; const { error:uploadError }=await supabase.storage.from("media").upload(path,file,{contentType:file.type,upsert:false}); if(uploadError) throw new Error(uploadError.message); const { error }=await supabase.from("media_assets").insert({file_name:file.name,storage_path:path,media_type:file.type.startsWith("image/")?"image":file.type.startsWith("video/")?"video":"document",mime_type:file.type,file_size:file.size,alt_text:alt||null,title:file.name,uploaded_by:user.id}); if(error){await supabase.storage.from("media").remove([path]);throw new Error(error.message);} revalidatePath("/admin/website/media"); }
